<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>PixivBatchBookmark</AssemblyName>
    <Version>1.0.2</Version>
    <ApplicationIcon>Assets/AppIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x64</Platforms>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PixivBatchBookmark.Core/PixivBatchBookmark.Core.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
    <Resource Include="Assets/AppIcon.ico" />
    <Resource Include="Assets/Wallpaper.png" />
  </ItemGroup>
</Project>
